__init__.py
import logging
import sys
from flask import Flask
from config import Config

def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)

    # Logging setup
    handler = logging.StreamHandler(sys.stdout)
    handler.setLevel(logging.INFO)
    fmt = logging.Formatter('%(asctime)s - %(levelname)s - %(message)s')
    handler.setFormatter(fmt)
    logging.getLogger().addHandler(handler)
    logging.getLogger().setLevel(logging.INFO)

    # Import and register blueprint
    from views import bp as views_bp
    app.register_blueprint(views_bp)

    return app

app = create_app()

views.py
import os
from flask import Blueprint, render_template, request, redirect, url_for, current_app
from werkzeug.utils import secure_filename

bp = Blueprint('views', __name__)

posts = []  # Temporary in-memory storage

@bp.route('/')
def index():
    return render_template('index.html', posts=posts)

@bp.route('/create', methods=['GET', 'POST'])
def create():
    if request.method == 'POST':
        title = request.form['title']
        author = request.form['author']
        body = request.form['body']
        image = request.files.get('image')

        filename = None
        if image and image.filename != '':
            filename = secure_filename(image.filename)
            image.save(os.path.join(current_app.config['UPLOAD_FOLDER'], filename))

        posts.append({
            'title': title,
            'author': author,
            'body': body,
            'image': filename
        })

        return redirect(url_for('views.index'))

    return render_template('create.html')

templates/create.html
<!DOCTYPE html>
<html>
<head>
    <title>Create Post</title>
</head>
<body>
    <h2>Create a New Post</h2>
    <form method="POST" enctype="multipart/form-data">
        <label>Title:</label><br>
        <input type="text" name="title" required><br><br>

        <label>Author:</label><br>
        <input type="text" name="author" required><br><br>

        <label>Body:</label><br>
        <textarea name="body" rows="4" cols="40" required></textarea><br><br>

        <label>Image:</label><br>
        <input type="file" name="image" accept="image/*"><br><br>

        <button type="submit">Submit Post</button>
    </form>

    <br>
    <a href="{{ url_for('views.index') }}">Back to Home</a>
</body>
</html>



   

templates/index.html
<!DOCTYPE html>
<html>
<head>
    <title>Posts Home</title>
</head>
<body>
    <h1>All Posts</h1>
    <a href="{{ url_for('views.create') }}">➕ Create New Post</a>
    <hr>

    {% for post in posts %}
        <h2>{{ post.title }}</h2>
        <p><b>Author:</b> {{ post.author }}</p>
        <p>{{ post.body }}</p>
        {% if post.image %}
            <img src="{{ url_for('static', filename='uploads/' + post.image) }}" width="200"><br>
        {% endif %}
        <hr>
    {% else %}
        <p>No posts yet!</p>
    {% endfor %}
</body>
</html>